import type { Family, Model } from "./types";

export const FAMILIES: { id: Family; label: string }[] = [
  { id: "qwen", label: "Qwen" },
  { id: "llama", label: "Llama" },
  { id: "gemma", label: "Gemma" },
  { id: "deepseek", label: "DeepSeek" },
  { id: "nemotron", label: "Nemotron" },
  { id: "ministral", label: "Ministral" },
  { id: "phi", label: "Phi" },
  { id: "other", label: "其他" },
];

export const MODELS: Model[] = [
  {
    id: "qwen25-05b",
    name: "Qwen2.5 0.5B",
    family: "qwen",
    paramsB: 0.49,
    layers: 24,
    attnLayers: 24,
    kvHeads: 2,
    headDim: 64,
    maxCtx: 32768,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "極小卡、嵌入式、分類／路由",
    note: "KV 極瘦（2 個 KV head、dim 64），6GB 完全不是問題。",
  },
  {
    id: "qwen25-15b",
    name: "Qwen2.5 1.5B",
    family: "qwen",
    paramsB: 1.54,
    layers: 28,
    attnLayers: 28,
    kvHeads: 2,
    headDim: 128,
    maxCtx: 32768,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "6GB 卡的翻譯／摘要",
  },
  {
    id: "qwen25-3b",
    name: "Qwen2.5 3B",
    family: "qwen",
    paramsB: 3.09,
    layers: 36,
    attnLayers: 36,
    kvHeads: 2,
    headDim: 128,
    maxCtx: 32768,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "小卡日常助手，KV 仍很省",
  },
  {
    id: "qwen25-7b",
    name: "Qwen2.5 7B",
    family: "qwen",
    paramsB: 7.61,
    layers: 28,
    attnLayers: 28,
    kvHeads: 4,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "日常聊天、翻譯、輕量 coding",
    note: "GQA 只有 4 個 KV head，長 context 相對省 VRAM。",
  },
  {
    id: "qwen25-14b",
    name: "Qwen2.5 14B",
    family: "qwen",
    paramsB: 14.7,
    layers: 48,
    attnLayers: 48,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "寫作、多輪助手、中等 coding",
  },
  {
    id: "qwen25-32b",
    name: "Qwen2.5 32B",
    family: "qwen",
    paramsB: 32.5,
    layers: 64,
    attnLayers: 64,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "主力 coding / 推理，單卡 24GB 甜區",
  },
  {
    id: "qwen25-coder-32b",
    name: "Qwen2.5 Coder 32B",
    family: "qwen",
    paramsB: 32.5,
    layers: 64,
    attnLayers: 64,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "本地 coding 專精，VRAM 與 32B 相同",
  },
  {
    id: "qwen25-72b",
    name: "Qwen2.5 72B",
    family: "qwen",
    paramsB: 72.7,
    layers: 80,
    attnLayers: 80,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "高品質推理與長文，需要 48GB 級",
  },
  {
    id: "qwen3-06b",
    name: "Qwen3 0.6B",
    family: "qwen",
    paramsB: 0.6,
    layers: 28,
    attnLayers: 28,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 32768,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "思考小模型，KV 相對 0.5B 肥",
    note: "8 個 KV head，長窗比 Qwen2.5-0.5B 貴很多。",
  },
  {
    id: "qwen3-17b",
    name: "Qwen3 1.7B",
    family: "qwen",
    paramsB: 1.7,
    layers: 28,
    attnLayers: 28,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 32768,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "6–8GB 思考／指令小模型",
  },
  {
    id: "qwen3-4b",
    name: "Qwen3 4B",
    family: "qwen",
    paramsB: 4.0,
    layers: 36,
    attnLayers: 36,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "6–8GB 卡的思考小模型",
  },
  {
    id: "qwen3-8b",
    name: "Qwen3 8B",
    family: "qwen",
    paramsB: 8.2,
    layers: 36,
    attnLayers: 36,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 40960,
    kind: "dense",
    purpose: "新一代 8B 主力，思考模式較強",
    note: "KV 比 Qwen2.5-7B 肥（8 KV head / 36 layer）。",
  },
  {
    id: "qwen3-14b",
    name: "Qwen3 14B",
    family: "qwen",
    paramsB: 14.8,
    layers: 40,
    attnLayers: 40,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 40960,
    kind: "dense",
    purpose: "16GB 卡的寫作與 coding 主力",
  },
  {
    id: "qwen3-32b",
    name: "Qwen3 32B",
    family: "qwen",
    paramsB: 32.8,
    layers: 64,
    attnLayers: 64,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 40960,
    kind: "dense",
    purpose: "24GB 卡的旗艦密集模型",
  },
  {
    id: "qwq-32b",
    name: "QwQ 32B",
    family: "qwen",
    paramsB: 32.8,
    layers: 64,
    attnLayers: 64,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "Qwen 系推理專精，VRAM 與 32B 相同",
  },
  {
    id: "qwen3-30b-a3b",
    name: "Qwen3 30B-A3B",
    family: "qwen",
    paramsB: 30.5,
    activeParamsB: 3.3,
    layers: 48,
    attnLayers: 48,
    kvHeads: 4,
    headDim: 128,
    maxCtx: 262144,
    nativeCtx: 32768,
    kind: "moe",
    purpose: "MoE：VRAM 像 30B，速度接近 8B",
    note: "權重要載入全部 expert，但 decode 只啟動約 3.3B。",
  },
  {
    id: "qwen3-235b-a22b",
    name: "Qwen3 235B-A22B",
    family: "qwen",
    paramsB: 235,
    activeParamsB: 22,
    layers: 94,
    attnLayers: 94,
    kvHeads: 4,
    headDim: 128,
    maxCtx: 262144,
    nativeCtx: 32768,
    kind: "moe",
    purpose: "旗艦 MoE 實驗，96GB 挑戰檔",
    note: "權重以總參數計；速度以 22B active 估算。",
  },
  {
    id: "llama32-1b",
    name: "Llama 3.2 1B",
    family: "llama",
    paramsB: 1.24,
    layers: 16,
    attnLayers: 16,
    kvHeads: 8,
    headDim: 64,
    maxCtx: 131072,
    nativeCtx: 131072,
    kind: "dense",
    purpose: "邊緣裝置、極低延遲",
  },
  {
    id: "llama32-3b",
    name: "Llama 3.2 3B",
    family: "llama",
    paramsB: 3.21,
    layers: 28,
    attnLayers: 28,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 131072,
    kind: "dense",
    purpose: "6–8GB 卡的輕量 Llama",
  },
  {
    id: "llama31-8b",
    name: "Llama 3.1 8B",
    family: "llama",
    paramsB: 8.03,
    layers: 32,
    attnLayers: 32,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "參考基準：GQA 8B 的 KV 教科書",
  },
  {
    id: "llama33-70b",
    name: "Llama 3.3 70B",
    family: "llama",
    paramsB: 70.6,
    layers: 80,
    attnLayers: 80,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "經典 70B，雙 3090 / 96GB 目標",
  },
  {
    id: "llama4-scout",
    name: "Llama 4 Scout",
    family: "llama",
    paramsB: 109,
    activeParamsB: 17,
    layers: 48,
    attnLayers: 48,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 262144,
    kind: "moe",
    purpose: "MoE：VRAM 像 109B，decode 接近 17B",
    note: "官方 context 可到千萬級；這裡上限 128K，因為 KV 會先爆。權重仍要載入全部 expert。",
  },
  {
    id: "gemma3-1b",
    name: "Gemma 3 1B",
    family: "gemma",
    paramsB: 1.0,
    layers: 26,
    attnLayers: 26,
    kvHeads: 1,
    headDim: 256,
    maxCtx: 32768,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "極小多語助手",
  },
  {
    id: "gemma3-4b",
    name: "Gemma 3 4B",
    family: "gemma",
    paramsB: 4.3,
    layers: 34,
    attnLayers: 34,
    kvHeads: 4,
    headDim: 256,
    maxCtx: 32768,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "小卡多語助手",
    note: "此處以文字 GGUF 估算；含 vision 的多模態權重會更大。",
  },
  {
    id: "gemma3-12b",
    name: "Gemma 3 12B",
    family: "gemma",
    paramsB: 12.2,
    layers: 48,
    attnLayers: 48,
    kvHeads: 8,
    headDim: 256,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "寫作與多語，KV 偏肥",
    note: "head dim 256，長 context 的 KV 比同尺寸 Qwen 明顯更大。",
  },
  {
    id: "gemma3-27b",
    name: "Gemma 3 27B",
    family: "gemma",
    paramsB: 27.4,
    layers: 62,
    attnLayers: 62,
    kvHeads: 16,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "高品質寫作，24GB 需盯 KV",
    note: "16 個 KV head，32K context 就可能吃掉十數 GB cache。",
  },
  {
    id: "r1-distill-8b",
    name: "R1 Distill Llama 8B",
    family: "deepseek",
    paramsB: 8.03,
    layers: 32,
    attnLayers: 32,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "8B 推理蒸餾，架構同 Llama 3.1 8B",
  },
  {
    id: "r1-distill-14b",
    name: "R1 Distill Qwen 14B",
    family: "deepseek",
    paramsB: 14.8,
    layers: 48,
    attnLayers: 48,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "14B 推理蒸餾，16GB Q4 主力",
  },
  {
    id: "r1-distill-32b",
    name: "R1 Distill Qwen 32B",
    family: "deepseek",
    paramsB: 32.8,
    layers: 64,
    attnLayers: 64,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "本地推理蒸餾檔，24GB Q4 主力",
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3 671B-A37B",
    family: "deepseek",
    paramsB: 671,
    activeParamsB: 37,
    layers: 61,
    attnLayers: 61,
    kvHeads: 1,
    headDim: 288,
    maxCtx: 131072,
    nativeCtx: 131072,
    kind: "moe",
    purpose: "旗艦 MoE：VRAM 極兇，MLA 讓 KV 相對瘦",
    note: "MLA 壓縮 KV（約 70 KiB/tok）。權重仍按 671B 計，需要多卡或 96GB 級狠量化。",
  },
  {
    id: "nemotron-nano-8b",
    name: "Nemotron Nano 8B",
    family: "nemotron",
    paramsB: 8.0,
    layers: 32,
    attnLayers: 32,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "NVIDIA 調教的 8B 指令／推理",
  },
  {
    id: "nemotron-super-49b",
    name: "Nemotron Super 49B",
    family: "nemotron",
    paramsB: 49.9,
    layers: 80,
    attnLayers: 80,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "70B 級能力、權重較小的 NAS 版",
    note: "Llama 3.3 Nemotron Super，層數與 KV 接近 70B。",
  },
  {
    id: "nemotron-70b",
    name: "Nemotron 70B",
    family: "nemotron",
    paramsB: 70.6,
    layers: 80,
    attnLayers: 80,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "高品質推理，需要雙卡或 96GB",
  },
  {
    id: "ministral3-3b",
    name: "Ministral 3 3B",
    family: "ministral",
    paramsB: 3.0,
    layers: 26,
    attnLayers: 26,
    kvHeads: 8,
    headDim: 96,
    maxCtx: 262144,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "極小卡／低延遲助手",
  },
  {
    id: "ministral3-8b",
    name: "Ministral 3 8B",
    family: "ministral",
    paramsB: 8.0,
    layers: 34,
    attnLayers: 34,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 262144,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "低延遲 coding 與指令",
  },
  {
    id: "ministral3-14b",
    name: "Ministral 3 14B",
    family: "ministral",
    paramsB: 14.0,
    layers: 40,
    attnLayers: 40,
    kvHeads: 8,
    headDim: 160,
    maxCtx: 262144,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "16GB 卡的 Mistral 系主力",
  },
  {
    id: "phi4-mini",
    name: "Phi-4 mini",
    family: "phi",
    paramsB: 3.84,
    layers: 32,
    attnLayers: 32,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 4096,
    kind: "dense",
    purpose: "小模型推理／數學，6GB 友善",
    note: "原生訓練 context 較短，長窗依 LongRoPE 外推。",
  },
  {
    id: "phi4",
    name: "Phi-4 14B",
    family: "phi",
    paramsB: 14.7,
    layers: 40,
    attnLayers: 40,
    kvHeads: 10,
    headDim: 128,
    maxCtx: 16384,
    nativeCtx: 16384,
    kind: "dense",
    purpose: "緊湊 14B，數學與推理密度高",
  },
  {
    id: "mistral-7b",
    name: "Mistral 7B",
    family: "other",
    paramsB: 7.25,
    layers: 32,
    attnLayers: 32,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 32768,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "經典 7B GQA 基準",
  },
  {
    id: "mistral-small-24b",
    name: "Mistral Small 24B",
    family: "other",
    paramsB: 24.0,
    layers: 40,
    attnLayers: 40,
    kvHeads: 8,
    headDim: 128,
    maxCtx: 131072,
    nativeCtx: 32768,
    kind: "dense",
    purpose: "24B 密集主力，速度與品質平衡",
  },
];

export const MODEL_BY_ID: Record<string, Model> = Object.fromEntries(
  MODELS.map((m) => [m.id, m]),
);

export const FAMILY_LABEL: Record<Family, string> = {
  qwen: "Qwen",
  llama: "Llama",
  gemma: "Gemma",
  deepseek: "DeepSeek",
  nemotron: "Nemotron",
  ministral: "Ministral",
  phi: "Phi",
  other: "其他",
};
